/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 *
 * 
 * XDoclet definition:
 * @struts.form name="BillMasterForm"
 */
public class BillMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** serviceNo property */
	private String serviceNo;
private int creditcardno;

	/** amount property */
	private int amount;

	/** billId property */
	private int billId;

	/** userId property */
	private int userId;

	/** employeId property */
	private int employeId;

	/** noOfUnits property */
	private int noOfUnits;

	/** billDate property */
	private String billDate;

	/** billNo property */
	private String billNo;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the serviceNo.
	 * @return String
	 */
	public String getServiceNo() {
		return serviceNo;
	}

	/** 
	 * Set the serviceNo.
	 * @param serviceNo The serviceNo to set
	 */
	public void setServiceNo(String serviceNo) {
		this.serviceNo = serviceNo;
	}

	/** 
	 * Returns the amount.
	 * @return int
	 */
	public int getAmount() {
		return amount;
	}

	/** 
	 * Set the amount.
	 * @param amount The amount to set
	 */
	public void setAmount(int amount) {
		this.amount = amount;
	}

	/** 
	 * Returns the billId.
	 * @return int
	 */
	public int getBillId() {
		return billId;
	}

	/** 
	 * Set the billId.
	 * @param billId The billId to set
	 */
	public void setBillId(int billId) {
		this.billId = billId;
	}

	/** 
	 * Returns the userId.
	 * @return int
	 */
	public int getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(int userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the employeId.
	 * @return int
	 */
	public int getEmployeId() {
		return employeId;
	}

	/** 
	 * Set the employeId.
	 * @param employeId The employeId to set
	 */
	public void setEmployeId(int employeId) {
		this.employeId = employeId;
	}

	/** 
	 * Returns the noOfUnits.
	 * @return int
	 */
	public int getNoOfUnits() {
		return noOfUnits;
	}

	/** 
	 * Set the noOfUnits.
	 * @param noOfUnits The noOfUnits to set
	 */
	public void setNoOfUnits(int noOfUnits) {
		this.noOfUnits = noOfUnits;
	}

	/** 
	 * Returns the billDate.
	 * @return String
	 */
	public String getBillDate() {
		return billDate;
	}

	/** 
	 * Set the billDate.
	 * @param billDate The billDate to set
	 */
	public void setBillDate(String billDate) {
		this.billDate = billDate;
	}

	/** 
	 * Returns the billNo.
	 * @return String
	 */
	public String getBillNo() {
		return billNo;
	}

	/** 
	 * Set the billNo.
	 * @param billNo The billNo to set
	 */
	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	public int getCreditcardno() {
		return creditcardno;
	}

	public void setCreditcardno(int creditcardno) {
		this.creditcardno = creditcardno;
	}
}