/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 *
 * 
 * XDoclet definition:
 * @struts.form name="CountryMasterForm"
 */
public class CountryMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** countryArea property */
	private int countryArea;

	/** countryName property */
	private String countryName;

	/** description property */
	private String description;

	/** abbr property */
	private String abbr;

	/** countryId property */
	private int countryId;

	/** countryMap property */
	private String countryMap;
private String countryMap1;
	/*
	 * Generated Methods
	 */

	public String getCountryMap1() {
	return countryMap1;
}

public void setCountryMap1(String countryMap1) {
	this.countryMap1 = countryMap1;
}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the countryArea.
	 * @return String
	 */
	public int getCountryArea() {
		return countryArea;
	}

	/** 
	 * Set the countryArea.
	 * @param countryArea The countryArea to set
	 */
	public void setCountryArea(int countryArea) {
		this.countryArea = countryArea;
	}

	/** 
	 * Returns the countryName.
	 * @return String
	 */
	public String getCountryName() {
		return countryName;
	}

	/** 
	 * Set the countryName.
	 * @param countryName The countryName to set
	 */
	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	/** 
	 * Returns the description.
	 * @return String
	 */
	public String getDescription() {
		return description;
	}

	/** 
	 * Set the description.
	 * @param description The description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/** 
	 * Returns the abbr.
	 * @return String
	 */
	public String getAbbr() {
		return abbr;
	}

	/** 
	 * Set the abbr.
	 * @param abbr The abbr to set
	 */
	public void setAbbr(String abbr) {
		this.abbr = abbr;
	}

	/** 
	 * Returns the countryId.
	 * @return int
	 */
	public int getCountryId() {
		return countryId;
	}

	/** 
	 * Set the countryId.
	 * @param countryId The countryId to set
	 */
	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	/** 
	 * Returns the countryMap.
	 * @return String
	 */
	public String getCountryMap() {
		return countryMap;
	}

	/** 
	 * Set the countryMap.
	 * @param countryMap The countryMap to set
	 */
	public void setCountryMap(String countryMap) {
		this.countryMap = countryMap;
	}
}