/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 *
 * 
 * XDoclet definition:
 * @struts.form name="CourierDetailsForm"
 */
public class CourierDetailsForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** amtCharged property */
	private String amtCharged;

	/** itemId property */
	private int itemId;

	/** courierId property */
	private int courierId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the amtCharged.
	 * @return String
	 */
	public String getAmtCharged() {
		return amtCharged;
	}

	/** 
	 * Set the amtCharged.
	 * @param amtCharged The amtCharged to set
	 */
	public void setAmtCharged(String amtCharged) {
		this.amtCharged = amtCharged;
	}

	/** 
	 * Returns the itemId.
	 * @return int
	 */
	public int getItemId() {
		return itemId;
	}

	/** 
	 * Set the itemId.
	 * @param itemId The itemId to set
	 */
	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	/** 
	 * Returns the courierId.
	 * @return int
	 */
	public int getCourierId() {
		return courierId;
	}

	/** 
	 * Set the courierId.
	 * @param courierId The courierId to set
	 */
	public void setCourierId(int courierId) {
		this.courierId = courierId;
	}
}