/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 *
 * 
 * XDoclet definition:
 * @struts.form name="CourierMasterForm"
 */
public class CourierMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */
	private String status;

	/** fromCityId property */
	private int fromCityId;

	/** userId property */
	private int userId;

	/** employeId property */
	private int employeId;

	/** courierDet property */
	private String courierDet;

	/** toCityId property */
	private int toCityId;

	/** fromCountryId property */
	private int fromCountryId;

	/** courierAmt property */
	private int courierAmt;

	/** toCountryId property */
	private int toCountryId;

	/** courierId property */
	private int courierId;

	/** courierDate property */
	private String courierDate;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the fromCityId.
	 * @return int
	 */
	public int getFromCityId() {
		return fromCityId;
	}

	/** 
	 * Set the fromCityId.
	 * @param fromCityId The fromCityId to set
	 */
	public void setFromCityId(int fromCityId) {
		this.fromCityId = fromCityId;
	}

	/** 
	 * Returns the userId.
	 * @return int
	 */
	public int getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(int userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the employeId.
	 * @return int
	 */
	public int getEmployeId() {
		return employeId;
	}

	/** 
	 * Set the employeId.
	 * @param employeId The employeId to set
	 */
	public void setEmployeId(int employeId) {
		this.employeId = employeId;
	}

	/** 
	 * Returns the courierDet.
	 * @return String
	 */
	public String getCourierDet() {
		return courierDet;
	}

	/** 
	 * Set the courierDet.
	 * @param courierDet The courierDet to set
	 */
	public void setCourierDet(String courierDet) {
		this.courierDet = courierDet;
	}

	/** 
	 * Returns the toCityId.
	 * @return int
	 */
	public int getToCityId() {
		return toCityId;
	}

	/** 
	 * Set the toCityId.
	 * @param toCityId The toCityId to set
	 */
	public void setToCityId(int toCityId) {
		this.toCityId = toCityId;
	}

	/** 
	 * Returns the fromCountryId.
	 * @return int
	 */
	public int getFromCountryId() {
		return fromCountryId;
	}

	/** 
	 * Set the fromCountryId.
	 * @param fromCountryId The fromCountryId to set
	 */
	public void setFromCountryId(int fromCountryId) {
		this.fromCountryId = fromCountryId;
	}

	/** 
	 * Returns the courierAmt.
	 * @return int
	 */
	public int getCourierAmt() {
		return courierAmt;
	}

	/** 
	 * Set the courierAmt.
	 * @param courierAmt The courierAmt to set
	 */
	public void setCourierAmt(int courierAmt) {
		this.courierAmt = courierAmt;
	}

	/** 
	 * Returns the toCountryId.
	 * @return int
	 */
	public int getToCountryId() {
		return toCountryId;
	}

	/** 
	 * Set the toCountryId.
	 * @param toCountryId The toCountryId to set
	 */
	public void setToCountryId(int toCountryId) {
		this.toCountryId = toCountryId;
	}

	/** 
	 * Returns the courierId.
	 * @return int
	 */
	public int getCourierId() {
		return courierId;
	}

	/** 
	 * Set the courierId.
	 * @param courierId The courierId to set
	 */
	public void setCourierId(int courierId) {
		this.courierId = courierId;
	}

	/** 
	 * Returns the courierDate.
	 * @return String
	 */
	public String getCourierDate() {
		return courierDate;
	}

	/** 
	 * Set the courierDate.
	 * @param courierDate The courierDate to set
	 */
	public void setCourierDate(String courierDate) {
		this.courierDate = courierDate;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
}