/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 *
 * 
 * XDoclet definition:
 * @struts.form name="EmployeMasterForm"
 */
public class EmployeMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** phone property */
	private String phone;
private String username;
private String password;
	/** employeMiddleName property */
	private String employeMiddleName;

	/** dateOfBirth property */
	private String dateOfBirth;

	/** userId property */
	private int userId;

	/** employeLastName property */
	private String employeLastName;

	/** dateOfJoin property */
	private String dateOfJoin;

	/** address property */
	private String address;

	/** employeId property */
	private int employeId;

	/** image property */
	private String image;

	/** email property */
	private String email;

	/** employeFirstName property */
	private String employeFirstName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the employeMiddleName.
	 * @return String
	 */
	public String getEmployeMiddleName() {
		return employeMiddleName;
	}

	/** 
	 * Set the employeMiddleName.
	 * @param employeMiddleName The employeMiddleName to set
	 */
	public void setEmployeMiddleName(String employeMiddleName) {
		this.employeMiddleName = employeMiddleName;
	}

	/** 
	 * Returns the dateOfBirth.
	 * @return String
	 */
	public String getDateOfBirth() {
		return dateOfBirth;
	}

	/** 
	 * Set the dateOfBirth.
	 * @param dateOfBirth The dateOfBirth to set
	 */
	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	/** 
	 * Returns the userId.
	 * @return int
	 */
	public int getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(int userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the employeLastName.
	 * @return String
	 */
	public String getEmployeLastName() {
		return employeLastName;
	}

	/** 
	 * Set the employeLastName.
	 * @param employeLastName The employeLastName to set
	 */
	public void setEmployeLastName(String employeLastName) {
		this.employeLastName = employeLastName;
	}

	/** 
	 * Returns the dateOfJoin.
	 * @return String
	 */
	public String getDateOfJoin() {
		return dateOfJoin;
	}

	/** 
	 * Set the dateOfJoin.
	 * @param dateOfJoin The dateOfJoin to set
	 */
	public void setDateOfJoin(String dateOfJoin) {
		this.dateOfJoin = dateOfJoin;
	}

	/** 
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/** 
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/** 
	 * Returns the employeId.
	 * @return int
	 */
	public int getEmployeId() {
		return employeId;
	}

	/** 
	 * Set the employeId.
	 * @param employeId The employeId to set
	 */
	public void setEmployeId(int employeId) {
		this.employeId = employeId;
	}

	/** 
	 * Returns the image.
	 * @return String
	 */
	public String getImage() {
		return image;
	}

	/** 
	 * Set the image.
	 * @param image The image to set
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/** 
	 * Returns the employeFirstName.
	 * @return String
	 */
	public String getEmployeFirstName() {
		return employeFirstName;
	}

	/** 
	 * Set the employeFirstName.
	 * @param employeFirstName The employeFirstName to set
	 */
	public void setEmployeFirstName(String employeFirstName) {
		this.employeFirstName = employeFirstName;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
}