/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts
 * 
 * XDoclet definition:
 * 
 * @struts.form name="GoodsDetailsForm"
 */
public class GoodsDetailsForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** price property */
	private int price;

	/** itemName property */
	private String itemName;

	private String goodsName;
	private String countryname;
	/** GoodsId property */
	private int goodsId;

	/** itemDesc property */
	private String itemDesc;

	/** itemImage property */
	private String itemImage;
	private String itemImage1;
	private String itemlanuch1;
	/** itemId property */
	private int itemId;

	/** itemLaunchVideo property */
	private String itemLaunchVideo;

	/** countryId property */
	private int countryId;

	/** itemRegDate property */
	private String itemRegDate;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the price.
	 * 
	 * @return int
	 */
	public int getPrice() {
		return price;
	}

	/**
	 * Set the price.
	 * 
	 * @param price
	 *            The price to set
	 */
	public void setPrice(int price) {
		this.price = price;
	}

	/**
	 * Returns the itemName.
	 * 
	 * @return String
	 */
	public String getItemName() {
		return itemName;
	}

	/**
	 * Set the itemName.
	 * 
	 * @param itemName
	 *            The itemName to set
	 */
	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	/**
	 * Returns the GoodsId.
	 * 
	 * @return int
	 */
	public int getGoodsId() {
		return goodsId;
	}

	/**
	 * Set the GoodsId.
	 * 
	 * @param GoodsId
	 *            The GoodsId to set
	 */
	public void setGoodsId(int goodsId) {
		this.goodsId = goodsId;
	}

	/**
	 * Returns the itemDesc.
	 * 
	 * @return String
	 */
	public String getItemDesc() {
		return itemDesc;
	}

	/**
	 * Set the itemDesc.
	 * 
	 * @param itemDesc
	 *            The itemDesc to set
	 */
	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	/**
	 * Returns the itemImage.
	 * 
	 * @return String
	 */
	public String getItemImage() {
		return itemImage;
	}

	/**
	 * Set the itemImage.
	 * 
	 * @param itemImage
	 *            The itemImage to set
	 */
	public void setItemImage(String itemImage) {
		this.itemImage = itemImage;
	}

	/**
	 * Returns the itemId.
	 * 
	 * @return int
	 */
	public int getItemId() {
		return itemId;
	}

	/**
	 * Set the itemId.
	 * 
	 * @param itemId
	 *            The itemId to set
	 */
	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	/**
	 * Returns the itemLaunchVideo.
	 * 
	 * @return String
	 */
	public String getItemLaunchVideo() {
		return itemLaunchVideo;
	}

	/**
	 * Set the itemLaunchVideo.
	 * 
	 * @param itemLaunchVideo
	 *            The itemLaunchVideo to set
	 */
	public void setItemLaunchVideo(String itemLaunchVideo) {
		this.itemLaunchVideo = itemLaunchVideo;
	}

	/**
	 * Returns the countryId.
	 * 
	 * @return int
	 */
	public int getCountryId() {
		return countryId;
	}

	/**
	 * Set the countryId.
	 * 
	 * @param countryId
	 *            The countryId to set
	 */
	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	/**
	 * Returns the itemRegDate.
	 * 
	 * @return String
	 */
	public String getItemRegDate() {
		return itemRegDate;
	}

	/**
	 * Set the itemRegDate.
	 * 
	 * @param itemRegDate
	 *            The itemRegDate to set
	 */
	public void setItemRegDate(String itemRegDate) {
		this.itemRegDate = itemRegDate;
	}

 

	public String getGoodsName() {
		return goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public String getCountryname() {
		return countryname;
	}

	public void setCountryname(String countryname) {
		this.countryname = countryname;
	}

	public String getItemImage1() {
		return itemImage1;
	}

	public void setItemImage1(String itemImage1) {
		this.itemImage1 = itemImage1;
	}

	public String getItemlanuch1() {
		return itemlanuch1;
	}

	public void setItemlanuch1(String itemlanuch1) {
		this.itemlanuch1 = itemlanuch1;
	}
}