/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 *
 * 
 * XDoclet definition:
 * @struts.form name="OrderShipmentMasterForm"
 */
public class OrderShipmentMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** userId property */
	private int userId;
	private String username;

	/** orderId property */
	private int orderId;

	/** shipmentDate property */
	private String shipmentDate;

	/** shipmentStatus property */
	private String shipmentStatus;

	/** shipmentId property */
	private int shipmentId;

	/** shipmentInchargeEmpId property */
	private int shipmentInchargeEmpId;

	/** customerFeedBack property */
	private String customerFeedBack;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the userId.
	 * @return int
	 */
	public int getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(int userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the orderId.
	 * @return int
	 */
	public int getOrderId() {
		return orderId;
	}

	/** 
	 * Set the orderId.
	 * @param orderId The orderId to set
	 */
	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	/** 
	 * Returns the shipmentDate.
	 * @return String
	 */
	public String getShipmentDate() {
		return shipmentDate;
	}

	/** 
	 * Set the shipmentDate.
	 * @param shipmentDate The shipmentDate to set
	 */
	public void setShipmentDate(String shipmentDate) {
		this.shipmentDate = shipmentDate;
	}

	/** 
	 * Returns the shipmentStatus.
	 * @return String
	 */
	public String getShipmentStatus() {
		return shipmentStatus;
	}

	/** 
	 * Set the shipmentStatus.
	 * @param shipmentStatus The shipmentStatus to set
	 */
	public void setShipmentStatus(String shipmentStatus) {
		this.shipmentStatus = shipmentStatus;
	}

	/** 
	 * Returns the shipmentId.
	 * @return int
	 */
	public int getShipmentId() {
		return shipmentId;
	}

	/** 
	 * Set the shipmentId.
	 * @param shipmentId The shipmentId to set
	 */
	public void setShipmentId(int shipmentId) {
		this.shipmentId = shipmentId;
	}

	/** 
	 * Returns the shipmentInchargeEmpId.
	 * @return int
	 */
	public int getShipmentInchargeEmpId() {
		return shipmentInchargeEmpId;
	}

	/** 
	 * Set the shipmentInchargeEmpId.
	 * @param shipmentInchargeEmpId The shipmentInchargeEmpId to set
	 */
	public void setShipmentInchargeEmpId(int shipmentInchargeEmpId) {
		this.shipmentInchargeEmpId = shipmentInchargeEmpId;
	}

	/** 
	 * Returns the customerFeedBack.
	 * @return String
	 */
	public String getCustomerFeedBack() {
		return customerFeedBack;
	}

	/** 
	 * Set the customerFeedBack.
	 * @param customerFeedBack The customerFeedBack to set
	 */
	public void setCustomerFeedBack(String customerFeedBack) {
		this.customerFeedBack = customerFeedBack;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
}