/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.iebms.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.iebms.dao.CourierMasterDao;

/** 
 * MyEclipse Struts
 *  
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class AdminviewCourierRequests extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try{
			CourierMasterDao dao=new CourierMasterDao();
			// int userid=((Integer)request.getSession().getAttribute("user")).intValue();
		     
			com.iebms.util.CoreList cl=dao.ViewAllCourierDetails();
int size=cl.size();
if(size!=0)
{
	request.setAttribute("ViewCourierRequests",cl);
	return mapping.findForward("ViewCourierRequests");
}
		
		}catch (Exception e) {
			// TODO: handle exception
		}
		return mapping.findForward("norecords");
	}
}