/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.iebms.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.iebms.dao.EmployeMasterDao;
import com.yourcompany.struts.form.EmployeMasterForm;

/** 
 * MyEclipse Struts
 *  
 * 
 * XDoclet definition:
 * @struts.action
 */
public class EmployeeRegisterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
			try{
				
			EmployeMasterForm aform=(EmployeMasterForm)form;
				EmployeMasterDao dao=new EmployeMasterDao();
				 boolean flag=dao.insertEmployeMaster(aform);
				 if(flag)
				 {
					 return mapping.findForward("registerSuccess");
				 }
				 }catch (Exception e) {
					// TODO: handle exception
				}
				 return mapping.findForward("registerFail");
}
}