/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.iebms.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.iebms.dao.GoodsMasterDao;
import com.iebms.util.CoreList;

/** 
 * MyEclipse Struts
 *  
 * 
 * XDoclet definition:
 * @struts.action path="/GoodsAction" name="GoodsMasterForm" parameter="submit" scope="request"
 * @struts.action-forward name="registerFail" path="/Success.jsp?status=Goods Addedtion  Failed"
 * @struts.action-forward name="registerSuccess" path="/Success.jsp?status=Goods Added Successfully"
 */
public class GeneralViewGoodsAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
	try{
		String storepath=request.getRealPath("/images");
		GoodsMasterDao dao=new GoodsMasterDao();
		CoreList acorelist=dao.ViewGoodsMaster();
		 int size=acorelist.size();
		 if(size!=0)
		 {
			 request.setAttribute("ViewGoods",acorelist);
			 return mapping.findForward("ViewGoods");
   	}
	}catch (Exception e) {
		// TODO: handle exception
	}
	return mapping.findForward("registerFail");
}
}