/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.iebms.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.iebms.dao.OrderShipmentMasterDao;
import com.yourcompany.struts.form.OrderShipmentMasterForm;

/** 
 * MyEclipse Struts
 *  
 * 
 * XDoclet definition:
 * @struts.action
 */
public class OrderShipmentAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try{
			OrderShipmentMasterForm aform=(OrderShipmentMasterForm)form;
			OrderShipmentMasterDao dao=new OrderShipmentMasterDao();
			boolean flag=dao.insertOrderShipmentMaster(aform);
			if(flag)
			{
				return mapping.findForward("registerSuccess");
			}

		}catch (Exception e) {
			// TODO: handle exception
		}
		return mapping.findForward("registerFail");
	}
}