/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.iebms.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.iebms.dao.GoodsMasterDao;
import com.yourcompany.struts.form.GoodsMasterForm;

/** 
 * MyEclipse Struts
 *  
 * 
 * XDoclet definition:
 * @struts.action path="/GoodsAction" name="GoodsMasterForm" parameter="submit" scope="request"
 * @struts.action-forward name="registerFail" path="/Success.jsp?status=Goods Addedtion  Failed"
 * @struts.action-forward name="registerSuccess" path="/Success.jsp?status=Goods Added Successfully"
 */
public class UpdateGoodsAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
	try{
		GoodsMasterForm aform=(GoodsMasterForm)form;
		GoodsMasterDao dao=new GoodsMasterDao();
		 boolean flag=dao.UpdateGoodsMaster(aform);
		 if(flag)
		 {return mapping.findForward("updateSuccess");
   	}
	}catch (Exception e) {
		// TODO: handle exception
	}
	return mapping.findForward("updateFail");
}
}