/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.iebms.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.iebms.dao.OrderShipmentMasterDao;
import com.iebms.util.CoreList;

/** 
 * MyEclipse Struts
 *  
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ViewOrderShipmentAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try{
			OrderShipmentMasterDao dao=new OrderShipmentMasterDao();
		int employeeid=((Integer)request.getSession().getAttribute("employeeid")).intValue();
		System.out.println("this is employeeeid"+employeeid);
			CoreList cl=dao.ViewOrderShipmentMaster(employeeid);
			int size=cl.size();
			if(size!=0)
			{
				request.setAttribute("ordershipmentmaster",cl);
				return mapping.findForward("ordershipmentmaster");
			}

		}catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		}
		return mapping.findForward("norecords");
	}
}